server:
  port: 5010
spring:
  application:
    name: poll-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/p_manager
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
