INSERT INTO t_question(id, title) VALUES(1, 'What Is The First Thing You Notice About A Person?');
INSERT INTO t_question(id, title) VALUES(2, 'What Are Some Challenges You Think The Next Generation Will Face?');
INSERT INTO t_question(id, title) VALUES(3, 'What Three Habits Will Improve Your Life?');
INSERT INTO t_question(id, title) VALUES(4, 'For What In Your Life Do You Feel Most Grateful?');
INSERT INTO t_question(id, title) VALUES(5, 'If You Could Have Lunch With One Person Alive Or Dead, Who Would It Be?');
INSERT INTO t_question(id, title) VALUES(6, 'What Is Your Favorite Season, And Why?');
INSERT INTO t_question(id, title) VALUES(7, 'Do You Have Any Guilty Pleasures?');
INSERT INTO t_question(id, title) VALUES(8, 'If You Could Only Eat One Food For The Rest Of Your Life, What Would It Be?');
INSERT INTO t_question(id, title) VALUES(9, 'What’s The Number One Item You Would Save From Your Burning House?');
INSERT INTO t_question(id, title) VALUES(10, 'What Really Makes You Angry?');